spring:
  profiles:
    include:
      - application-stomp.yml
    active: dev
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    #url: ENC(AmjDJqwXWxXbNLxT2tqrt7evRCK8NdAJ/KVEtB7usTsoUzlncqDsMcIiJbPEo2eR7470koIhMEpI1Ut2Ywum/kwxsbK3eM7x) 외부 아이피
    url: jdbc:mysql://localhost:3306/worm?serverTimezone=Asia/Seoul
    username: ENC(5/AhqAagHOPYLAK/ZmVpWQ==)
    password: ENC(7tcKhS5JXkdK1pfbDxbgHA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
server:
  port: 80