spring:
  profiles:
    include:
      - application-stomp.yml
  datasource:
    url: ENC(DJ5nCdC4anos5LC0QwbzHs6fTWZgITh9FizxMvb4nvKRCD0RaRCBRh84lumw0GgGIYuZ1p0o0gYsrzMdWMXmwYWoEB92I9/OjOZN5XKUYtYpVhXTZ0uJCxYxYq9bfM11)
    username: ENC(0Ev7369tmM7eVMWpDe9waw==)
    password: ENC(xrVfu7ieAx/1bR3pXqshew==)
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100
          use_sql_comments: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
