spring:
  profiles:
    include:
      - application-stomp.yml
  active: dev

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cash: false

    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100
          use_sql_comments: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---

Spring:
  profiles: dev

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  devtools:
    livereload:
      enabled: true
---

spring:
  profiles: live
  datasource:
    url: ENC(AmjDJqwXWxXbNLxT2tqrt7evRCK8NdAJ/KVEtB7usTsoUzlncqDsMcIiJbPEo2eR7470koIhMEpI1Ut2Ywum/kwxsbK3eM7x)
    username: ENC(5/AhqAagHOPYLAK/ZmVpWQ==)
    password: ENC(7tcKhS5JXkdK1pfbDxbgHA==)
    driver-class-name: com.mysql.cj.jdbc.Driver